### PR TITLE
RPC Documentation

### PR DESCRIPTION
**Pull request by giovannivignone**
# Overview
PR for RPC documentation given issue #135 

## Changes
- Adding a rpc.md with a table of supported rpc methods.
- Linking to the rpc.md from readme.md

### CODE REVIEW

**Review by ncitron — CHANGES_REQUESTED** [review]
This looks mostly good to me. However, the rpc methods refers to the jsonrpc methods, not the client interface. For example, the client's `get_balance` is actually `eth_getBalance`. Can we use these instead? Also think its ok to remove the examples once we switch to this since the rpc is very well documented.

**Comment by giovannivignone** [comment]
Yup no problem. @ncitron Basically change every left value in the table into the actual JSON RPC method, not the helios specific ones in rust and remove the examples? 

Just one question: shouldn't we display somewhere in this documentation how to actually call these methods with helios (like shouldn't we include the information that get_block() on the client is how you call eth_getBlock JSON RPC)?

**Comment by refcell** [comment]
> This looks mostly good to me. However, the rpc methods refers to the jsonrpc methods, not the client interface. For example, the client's `get_balance` is actually `eth_getBalance`. Can we use these instead? Also think its ok to remove the examples once we switch to this since the rpc is very well documented.

+1 Maybe split the methods into two columns, something like:

```markdown
| RPC Method | Client Function |  Description | Example |
| ------------ | --------------- | ------------- | --------- |
```

**Comment by ncitron** [comment]
Agreed @refcell

**Review by refcell — APPROVED** [review]
LGTM

**Review by ncitron — APPROVED** [review]
LGTM

**Pull request merged**
