### PR TITLE
feat/added op_stack networks

### PR DESCRIPTION
**Pull request by varun-doshi**
Related https://github.com/a16z/helios/issues/410

The following networks have been added:
- Worlchain
- Unichain
- Zora

### CODE REVIEW

**Comment by varun-doshi** [comment]
Ink was not added since I was unable to find their network config(i believe their testnet rolls out in 2 weeks or so)

Should I add the following networks as well?
- opBnB
- Magi
- Manta network


Should I go ahead and update the `index.html` and `README.md` files by adding the new networks?

**Comment by ncitron** [comment]
These are good for now. One issue is that the unsafe signers don't look correct. We need to track this down from the SystemConfig contract from [here](https://github.com/ethereum-optimism/superchain-registry/tree/main/superchain/configs/mainnet) and view the contract on Etherscan and read the `unsafeBlockSigner` from the contract (under contract -> read as proxy). Looks like only Worldchain and Zora or not in testnet from my list so we should start with those two.

**Comment by mw2000** [comment]
@varun-doshi 

Was going the helios codebase this weekend so found some of these constants. Posting it here to help 

Unsafe signers for 
Zora -> `3Dc8Dfd0709C835cAd15a6A27e089FF4cF4C9228`
Worldchain -> `2270d6eC8E760daA317DD978cFB98C8f144B1f3A`

Found these from the SystemConfig contracts on L2 beat:
https://l2beat.com/scaling/projects/world#contracts
https://l2beat.com/scaling/projects/zora#contracts

Etherscan contracts link for SystemConfig:
Zora -> https://etherscan.io/address/0xA3cAB0126d5F504B071b81a3e8A2BBBF17930d86#code
Worldchain -> https://etherscan.io/address/0x6ab0777fD0e609CE58F939a7F70Fe41F5Aa6300A#code

**Comment by varun-doshi** [comment]
> @varun-doshi
> 
> Was going through the helios codebase this weekend so found some of these constants. Posting it here to help
> 
> Unsafe signers for Zora -> `3Dc8Dfd0709C835cAd15a6A27e089FF4cF4C9228` Worldchain -> `2270d6eC8E760daA317DD978cFB98C8f144B1f3A`
> 
> Found these from the SystemConfig contracts on L2 beat: https://l2beat.com/scaling/projects/world#contracts https://l2beat.com/scaling/projects/zora#contracts
> 
> Etherscan contracts link for SystemConfig: Zora -> https://etherscan.io/address/0xA3cAB0126d5F504B071b81a3e8A2BBBF17930d86#code Worldchain -> https://etherscan.io/address/0x6ab0777fD0e609CE58F939a7F70Fe41F5Aa6300A#code

Thank for the heads up @mw2000

**Comment by varun-doshi** [comment]
> These are good for now. One issue is that the unsafe signers don't look correct. We need to track this down from the SystemConfig contract from [here](https://github.com/ethereum-optimism/superchain-registry/tree/main/superchain/configs/mainnet) and view the contract on Etherscan and read the `unsafeBlockSigner` from the contract (under contract -> read as proxy). Looks like only Worldchain and Zora or not in testnet from my list so we should start with those two.

Fixed the signers for Worldchain and Zora. Unichain is still under development.
I was thinking we could add `Cyber` here as well(?)

**Comment by ncitron** [comment]
Lets remove unichain for now then. As for Cyber, I think we want to stick with major chains for now unless there's demand from Helios users.

**Review by ncitron — APPROVED** [review]
LGTM!

**Pull request merged**
