### PR TITLE
fixes #380 | fixes get_filter_changes() function

### LINKED ISSUE #380: fix: get_filter_changes() function in client.rs
In the client.rs file, the function there is a function called `get_filter_changes()` which is incorrect. It calls `self.node.uninstall_filter()` instead of `self.node.get_filter_changes()`

{C87940A1-A409-4038-ACE3-0FF668B2144D}

### PR DESCRIPTION
**Pull request by 18aaddy**
This PR fixes #380
I have updated the function to return correct value and call the correct function.
Working locally ✅

### CODE REVIEW

**Comment by 18aaddy** [comment]
@ncitron can you review pls?

**Comment by ncitron** [comment]
Sorry we were working on some big changes to Helios so this will need to be redone against the current master. Looks like the bug is still there though. Good catch! The location of that file is now in `core/client/mod.rs`

**Comment by 18aaddy** [comment]
Yes sure I'll update the PR

**Comment by 18aaddy** [comment]
✅ Rebased this branch

**Pull request merged**
