### PR TITLE
chore: rename optimism to op-mainnet

### PR DESCRIPTION
**Pull request by MuhtasimTanmoy**
Closes https://github.com/a16z/helios/issues/421

### CODE REVIEW

**Comment by ncitron** [comment]
Let's update the operationsolarstorm endpoint as well for constancy. I'll make sure to add an alias to that url.

**Comment by MuhtasimTanmoy** [comment]
> Let's update the operationsolarstorm endpoint as well for consistency. I'll make sure to add an alias to that url.

@ncitron Sure. 

Btw, I ran `cargo test-all` after replacing `.env` with Alchemy API Key before pushing.

Output:

```
running 4 tests
test get_balance ... FAILED
test get_transaction_receipt ... FAILED
test call ... FAILED
test get_transaction_by_hash ... FAILED

failures:

---- get_balance stdout ----
thread 'get_balance' panicked at tests/rpc_equivalence.rs:22:59:
called `Result::unwrap()` on an `Err` value: NotPresent

---- get_transaction_receipt stdout ----
thread 'get_transaction_receipt' panicked at tests/rpc_equivalence.rs:22:59:
called `Result::unwrap()` on an `Err` value: NotPresent

---- call stdout ----
thread 'call' panicked at tests/rpc_equivalence.rs:22:59:
called `Result::unwrap()` on an `Err` value: NotPresent
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- get_transaction_by_hash stdout ----
thread 'get_transaction_by_hash' panicked at tests/rpc_equivalence.rs:22:59:
called `Result::unwrap()` on an `Err` value: NotPresent


failures:
    call
    get_balance
    get_transaction_by_hash
    get_transaction_receipt

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

Is this something I should be concerned about?

**Comment by ncitron** [comment]
Yeah thats fine. Those env vars get injected by our CI which is why it fails locally.

**Comment by ncitron** [comment]
Did you push your commit to update the URLs?

**Comment by MuhtasimTanmoy** [comment]
> I'll make sure to add an alias to that URL.
What should be the new URLs?

**Comment by ncitron** [comment]
We should change all instances of `optimism.operationsolarstorm.org` to `op-mainnet.operationsolarstorm.org`

**Comment by MuhtasimTanmoy** [comment]
And this?

> file: opstack/src/server/net/block_handler.rs

```
blocks_v3_topic: IdentTopic::new(format!("/optimism/{}/2/blocks", chain_id)) 
```

**Comment by ncitron** [comment]
No this stays the same

**Comment by MuhtasimTanmoy** [comment]
done

**Review by ncitron — APPROVED** [review]
LGTM!

**Comment by ncitron** [comment]
Before we merge can you run `cargo fmt`?

**Comment by MuhtasimTanmoy** [comment]
> Before we merge can you run cargo fmt?

Done. What about clippy errors?

**Comment by MuhtasimTanmoy** [comment]
Any dependency?

**Pull request merged**
